[package]
name = "native-page-layer"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "native_page_layer"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"
objc2 = "0.5"

[build-dependencies]
napi-build = "2"
