// Re-export from shared module — preserves import paths for existing consumers
export {
  COMMAND_LABELS,
  MUTATION_VERBS,
  GLOBAL_AB_FLAGS,
  splitShellArgs,
  shellQuote,
  splitChainedCommands,
  parseCommandArgs,
  effectiveBrowseCommand,
  mutationVerbForCommand,
  labelKeyForCommand,
  parseTargetQuery,
  parseScrollTarget,
  invalidateCdpCache,
  resolveAgentBrowserPath,
  spawnAsync,
  handleBrowse,
  staleGenerationWarning,
} from './shared/browse-handler'
